import { readFileSync, writeFileSync } from 'fs';

const translations = {
  aatrox: ["Q deals [[AIRBORNE]] only when hitting at the edge", "W has no [[TRUE_SIGHT]] in the tooltip,\nbut the effect works the same", "E's base effect includes [[LIFESTEAL]] on all damage to champions,\nso it applies to basic attacks, Q, W, item effects, etc."],
  ahri: ["P's [[HEAL]] activates at 9 stacks.\nGain 1 stack from killing minions or monsters.\nKill participation within 3s triggers ~18 stacks instantly\n(stacks are not consumed when triggered this way)", "Kill participation during R's duration\ngrants +1 R charge and extends its duration"],
  akali: ["Q's [[SLOW]] only applies when hitting at max range", "W grants [[INVISIBILITY]] only inside the shroud.\nIf hit by a [[REVEALED]] ability (e.g. Lee Sin E) after hiding, you become visible.\nHiding before being hit keeps you hidden.\nTrue sight (e.g. Lee Sin Q) always reveals you", "E can be thrown into the shroud and recalled with E2.\nE2 cannot target [[UNTARGETABLE]] units"],
  akshan: ["Q [[PIERCE]]s on hit and gains bonus range, repeating until it misses", "W's [[REVIVE]] triggers under specific conditions.\nA Scoundrel is an enemy who killed an ally within 60s.\nKilling or assisting a Scoundrel within 3s instantly [[REVIVE]]s allies that Scoundrel killed.\nOther Scoundrel marks are removed", "E scales along walls. Landing near the target via E reuse causes less DPS loss than right-clicking to land", "Can wall-travel with E while channeling R", "If the target uses [[CAMOUFLAGE]] or [[INVISIBILITY]] after R is cast,\nthey become hidden but R still tracks them"],
  alistar: ["P's [[HEAL]] gains 1 stack from landing CC or when a nearby enemy minion dies.\nAt 7 stacks per champion or epic monster, heals Alistar and a nearby ally", "Disabling smartcast on W makes the Pulverize-Headbutt combo easier", "R is best used after getting hit by CC.\nR has no [[TENACITY]].\nUsing R's [[CC_CLEANSE]] to remove persistent CC will reapply it (e.g. Kog'Maw E [[SLOW]], Graves W [[SLOW]])", "Cleansing [[AIRBORNE]] with R stops movement but still allows skill use.\nHowever, W may be bugged — the charge triggers but the skill is nullified: the target is not knocked back and takes no damage"],
  ambessa: ["[[WALL_HOP]] via Ambessa's P is not possible", "P's [[ENERGY_RESTORE]] works by building buff stacks from using skills and consuming those stacks with basic attacks to restore energy", "R's [[LIFESTEAL]] and [[AR_PEN]] are passive effects, so all skills effectively lifesteal after learning R", "R only hits the rearmost enemy champion in its path"],
  amumu: ["R cannot be cast while flying with Q"],
  anivia: ["[[Q_FLASH]] not possible", "P (Egg) cooldown is 240s.\nCannot TP onto the egg.\n[[GW]] applies to the egg but it revives at full HP anyway", "Q applies [[SLOW]] via chill to enemies standing in its path.\nReactivating it detonates the explosion and applies [[STUN]]", "E's description is slightly misleading.\nIt says double damage on chilled targets, but E actually double-damages targets with Frostbite (the frozen debuff).\nQ and R both chill, but Frostbite from Q is instant while R's Frostbite only applies after the field fully expands", "That's why RE sometimes fails to double-damage — R hasn't fully expanded yet before E hits.\nWait briefly after R before throwing E to get the expected damage"],
  annie: ["P's [[STUN]] applies on Q, W, or R when at 4 stacks", "R has [[MR_PEN]] as a passive effect"],
  aphelios: ["Weapon order: Calibrum→Severum→Gravitum→Infernum→Crescendum (or Moonlit→Crimson→Gravitum→Infernum→Flare)", "Calibrum (green)", "Severum (red) is melee range.\nQ [[LIFESTEAL]] generates [[SHIELD]] when at max HP", "Infernum (blue): if two enemies are lined up, aiming at the front one lets the back one get hit by the cone blast; aiming at the back one damages the front one as the projectile passes through.\nDamage mechanics vary per target", "Crescendum (white) Q turret allows [[ALLY_TP_OK]]", "R deals area damage then auto-attacks all hit targets once with the current weapon"],
  ashe: ["[[W_FLASH]] works but mouse aim is important.\nW itself has no [[SLOW]] — the [[SLOW]] comes from P", "E reveals targets inside brushes"],
  aurelionsol: ["[[R_FLASH]] works by using R outside range then flashing"],
  aurora: ["[[R_FLASH]] not possible", "E has two phases: 1. Wind-up, 2. Retreat.\nIf hit by CC during phase 1, Aurora ignores it and phase 2 still triggers"],
  azir: ["[[Q_FLASH]] and [[R_FLASH]] not possible", "Cannot TP onto soldiers", "Azir's E travel distance is shorter than expected.\nCast E then immediately Q before arriving to travel farther.\nQ can also redirect the path"],
  bard: ["P's [[SLOW]] activates at 5 stacks.\nMore stacks increase various effects", "Q applies [[SLOW]] on a straight hit.\nPiercing through another enemy or hitting a wall applies [[STUN]]", "W gains power over time when left on the ground.\nEnemies stepping on it destroy it", "Allies and enemies can attack you during E travel.\nBeing hit by CC ejects you from the wall"],
  belveth: ["[[AS_UP]] increases and [[GHOSTING]] activates after using a skill", "Void Coral spawns allow [[ALLY_TP_OK]]", "[[WALL_HOP]] on Q is only available in R (Endless Banquet) form", "[[W_FLASH]] not possible", "E cancels if hit by CC during cast"],
  blitzcrank: ["[[Q_FLASH]] not possible", "W applies a self [[SLOW]] when its duration expires"],
  brand: ["P's [[MANA_RESTORE]] triggers when killing a target with Blaze.\nBlaze stacks up to 3 per target from skills.\nAt 3 stacks it triggers an AoE explosion.\nItem effects (e.g. Liandry's, Luden's) don't proc it", "Q's [[STUN]] only applies to targets already affected by Blaze (e.g. WQ, EQ, RQ)", "R's [[SLOW]] only applies to targets already affected by Blaze"],
  braum: ["E blocks the first incoming projectile's damage", "E's blocking concept has two categories:\n1. [[DAMAGE_NULLIFY]] — nullifies the first hit on Braum\n2. [[INTERCEPT_PROJECTILE]] — intercepts projectiles aimed at allies (projectile deleted)", "Per-champion E data focuses on cases where normally unblockable projectiles become blockable", "Using E then Zhonya's prevents E from activating", "[[R_FLASH]] not possible.\nR applies [[AIRBORNE]] for 1s on the first target and 0.6s on others"],
  briar: ["Briar's [[LIFESTEAL]] is exceptional — [[GW]] is essential against her", "E's [[STUN]] requires the target to collide with a wall"],
  caitlyn: ["P stacks charge at 2 per bush auto.\nW (Yordle Snap Trap) also deals bonus damage to trapped targets", "[[Q_FLASH]] not possible.\nQ damage decreases per additional target pierced.\nHowever Q always deals 100% damage to targets trapped by W", "Cannot TP onto W (traps)", "E applies [[AA_RESET]] on hit"],
  camille: ["P: the shield type reflects the higher proportion of incoming physical/magic damage received.\nExample: if Camille has 30 armor / 50 MR and takes 100 physical / 100 magic damage,\nmore physical damage goes through, so she gets a physical shield", "W applies [[HEAL]] and [[SLOW]] only when hitting with the outer ring", "E has three phases: lunge / grapple / dash.\nCC hit during the lunge phase is valid but the grapple still pulls Camille to the wall.\nThere is no CC immunity during the grapple or dash phases", "E works on most terrain walls.\n[[AS_UP]] and [[STUN]] only trigger on collision with an enemy", "R traps the target inside an arena, and nearby enemy champions are [[KNOCKBACK]]ed out when the arena expands"],
  cassiopeia: ["Boots can now be purchased", "Q [[MS_UP]] only applies if the shot lands", "R applies [[STUN]] to enemies facing Cassiopeia, and [[SLOW]] to those facing away"],
  chogath: ["R (Feast) is listed as [[HEAL]] because it increases max HP on kill,\nbut [[GW]] does not apply"],
  corki: ["[[R_FLASH]] requires a slight delay after pressing R — using flash immediately cancels it", "W is interrupted by [[AIRBORNE]] (please report if other CC types also interrupt it)"],
  darius: ["P applies [[AD_UP]] at 5 stacks or on R last-hit", "Q applies P stacks and [[HEAL]] only when hitting with the outer edge", "E's [[AR_PEN]] is a passive effect", "R deals bonus damage per P stack.\nKilling with R:\n1st/2nd rank: R can be recast for 20s. It disappears if unused.\n3rd rank: full cooldown reset that doesn't expire", "If the target disappears or uses Zhonya's mid-cast, R's cooldown doesn't start — it can be reused immediately (except vs Shaco R)"],
  diana: ["P has a level-based [[AS_UP]] plus additional [[AS_UP]] from using skills", "Fully detonating all W spheres grants a bonus [[SHIELD]]", "E+Q does not reset E"],
  draven: ["Q does not [[AA_RESET]]", "After R deals damage, if the target's remaining HP is lower than Draven's stack bonus, they are executed.\nExample: target HP 1000, R damage 300, stack bonus 700 → execute"],
  drmundo: ["[[Q_FLASH]] not possible.\nQ (Infected Bonesaw) heals 50 HP when it lands", "Using W and taking damage, then letting it detonate on an enemy champion heals 100% of grey health.\nSummary: activate W and get in their face"],
  ekko: ["W creates a slow field.\nThe effect activates as long as enemies enter before it disappears"],
  elise: ["Spider form Q cannot hop walls", "Spider form E reveals inside brushes.\n[[LIFESTEAL]] is correct, not a typo.\nThe exact mechanic: using Spider E to descend on a target increases Elise's P passive effect, boosting [[LIFESTEAL]]"],
  evelynn: ["[[CAMOUFLAGE]] does not break on flash", "W's [[CHARM]] and [[MR_SHRED]] are secondary effects triggered only by attacking a target with full stacks", "E's dash is empowered while in [[CAMOUFLAGE]].\nE can [[WALL_HOP]] under very specific conditions", "R deals increased damage to targets below 30% HP"],
  ezreal: ["P is a stacking buff that must be maintained with skills", "[[E_FLASH]] fires from the flash destination", "[[R_FLASH]] technically works but since R fires from Ezreal's original position, it's classified as not possible"],
  fiddlesticks: ["Cannot TP onto the effigy", "Q [[FEAR]] is a persistent passive.\nBeing out of combat, outside vision, or standing still for 2s (pretending to be the effigy) activates the condition.\nDealing damage with a skill then triggers [[FEAR]].\n[[FEAR]] has a per-champion cooldown shown as a circular timer around the target"],
  fizz: ["Q wall-hop only works by targeting an enemy across the wall", "E's [[SLOW]] only applies if landing without recasting", "R's [[SLOW]] applies twice:\n1. When the fish hits\n2. When the shark bites", "Place mouse far away before using R for maximum range"],
  galio: ["[[W_FLASH]] not possible (patched).\nDisabling smartcast on W is recommended", "[[E_FLASH]] not possible", "E has two phases: wind-up / dash.\nCC hit during wind-up is valid, but Galio still dashes forward.\nThere is no CC immunity during the dash phase"],
  gangplank: ["Powder keg count is shown below the mana bar"],
  garen: ["Using W before a CC hits reduces the CC duration significantly", "E hit count increases with attack speed.\n[[AR_SHRED]] applies after hitting 6 or more times", "E cannot be cancelled by any CC"],
  gnar: ["Gnar transforms when rage reaches 100 and a skill is used.\nMini E (hop) landing on a target double-jumps and triggers the transform", "Mini form:\nP [[MS_UP]] is always active in mini form.\n[[Q_FLASH]] not possible.\nE applies [[SLOW]] on hit — minions can also be hopped on.\nR amplifies W [[MS_UP]]", "Mega form:\nP is [[MAX_HP_UP]] so [[GW]] has no effect.\n[[W_FLASH]] not possible.\nR requires hitting a wall for [[STUN]]"],
  gragas: ["Q and R can be cast mid-flight during E"],
  graves: ["Autoattacking while hugging a thick wall with E creates extremely fast AA cancels", "W's [[SLOW]] continuously applies to targets inside the area", "If interrupted during R cast, the projectile still fires but movement may be restricted depending on the situation"],
  gwen: ["Q is most effective when hitting with the center", "W blocks projectiles originating from outside its area.\nTargeted projectiles already flying toward Gwen are also blocked if W is activated before they arrive"],
  hecarim: ["[[Q_FLASH]], [[W_FLASH]], [[E_FLASH]], [[R_FLASH]] all not possible", "Hecarim gains [[AD_UP]] based on bonus movement speed", "E has two phases: charge / strike.\nCC during the charge phase is valid but doesn't cancel E.\nOnce the strike phase activates (rearing up), CC is ignored", "R's [[FEAR]] has inconsistent hit detection.\nEnemies using mobility at the right timing can often dodge it easily"],
  heimerdinger: ["P's [[MS_UP]] only activates near Q (turrets) or allied towers", "[[W_FLASH]] and [[E_FLASH]] not possible", "E must hit the center to apply [[STUN]]"],
  hwei: ["Hwei's skills are easiest to memorize by color", "Q skills (red — damage):\nQW deals bonus damage to isolated or CC'd targets", "W skills (blue — utility)", "E skills (purple — CC):\nEW travels and expands after a delay.\nIf an enemy champion is within range when it expands, it launches a homing projectile.\nThe projectile can be blocked by other units (minions, jungle monsters, etc.)"],
  illaoi: ["[[Q_FLASH]] not possible", "Each tentacle hit heals based on missing HP, so effectively Q, W, E, R all [[HEAL]]", "Illaoi's E cannot pierce minions.\nHitting an enemy champion extracts their soul.\nDamaging the soul transfers damage to the body.\nIf the soul reaches 0 HP or leaves the area, it returns to the body applying [[SLOW]] and a mark"],
  irelia: ["[[E_FLASH]] not possible", "P stacks up to 4.\nStacks are maintained only by hitting champions or towers"],
  ivern: ["[[Q_FLASH]] not possible", "W explodes after a delay.\nHitting an enemy with the explosion applies [[SLOW]].\nIf no enemy is hit, Ivern gains a bonus shield"],
  janna: ["P's [[MS_UP]] applies to nearby allies", "[[Q_FLASH]] and [[R_FLASH]] not possible", "W's [[GHOSTING]] disappears when on cooldown"],
  jarvaniv: ["Q's [[AIRBORNE]] requires hitting the E (flag)", "E provides [[AS_UP]] to nearby allies", "W's shield increases with more enemy champions hit", "If a target flashes after R is cast, they can escape"],
  jax: ["P stacks up to 8", "After learning R, always think 'beat-beat-hit' in your head.\nAfter using R it changes to 'beat-hit'.\nOn the 'hit' rhythm, attack the enemy"],
  jayce: ["Hammer form basic attacks restore mana", "P's [[MS_UP]] activates on every form swap", "Swapping to cannon form then auto-attacking applies [[AR_MR_SHRED]] to the target", "Hammer form E is [[INSEC_KICK]] capable"],
  jhin: ["P's [[MS_UP]] triggers on crit with a basic attack", "Holding the 4th shot increases movement speed.\nPlacing traps to extend the 4th shot buff is effective", "W's [[ROOT]] activates when the target receives any damage or debuff", "E's [[SLOW]] applies continuously to enemies standing in the trap area"],
  jinx: ["[[W_FLASH]], [[E_FLASH]], [[R_FLASH]] all not possible", "P [[MS_UP]] only activates from champions, epic monsters, or structures", "Q: Minigun mode ([[AS_UP]])\nFishbones mode (splash damage, increased range)", "E's [[ROOT]] has better hitbox detection than most roots and interrupts many dashes"],
  kaisa: ["Evolutions:\nQ — 100 bonus AD\nW — 100 AP\nE — 100% AS", "Evolved W reduces its cooldown when hitting an enemy champion"],
  karma: ["Mantra W heals on activation.\nIf the [[TETHER]] triggers and [[ROOT]] is applied, it heals again"],
  karthus: ["Q deals increased damage to a single target", "Using flash during R channeling cancels R immediately — never do this"],
  kassadin: ["P's [[DMG_REDUCE]] applies to magic damage only", "Q has channel interruption (not silence)"],
  katarina: ["Cannot TP onto daggers", "E teleports Katarina near the target and strikes.\nCasting on the target or nearby ground moves her to that position"],
  kayle: ["[[Q_FLASH]] not possible", "P activates after putting points in E.\nP's [[MS_UP]] triggers during autos at 5 stacks", "Leveling R at 6/11/16 provides upgrades:\n6: [[RANGE_UP]]\n11: auto-attacks at 5 stacks fire a flame wave (AoE + bonus damage; basic attacks only hit one target)\n16: additional [[RANGE_UP]] + permanent 5-stack effect"],
  kayn: ["Pre-transformation Kayn is very weak", "Darkin P's [[LIFESTEAL]] applies to all abilities"],
  kennen: ["Q flash not possible", "P at 3 stacks applies a stun", "E's [[AS_UP]] activates on deactivation", "R cannot be cancelled by any CC"],
  khazix: ["P's [[SLOW]] activates when Kha'Zix is invisible to the target", "W [[HEAL]] only activates when standing inside the explosion radius", "[[INVISIBILITY]] does not break on flash.\nE (jump) does break it", "Skills can be cast while mid-air from E"],
  kindred: ["R flash not possible", "Each mark increases Q [[AS_UP]] by 5%, W and E damage, and range by 75 every 4 marks", "Jungle marks appear to be random", "R grants [[INVULNERABLE]] below 10% HP"],
  kled: ["Mounted:\nQ must remain in contact to apply [[GRAB]] and [[SLOW]].\nE grants [[MS_UP]] on first hit and becomes recastable", "Neither mounted nor dismounted W can AA cancel", "Unsure if [[GW]] affects mounted healing — please report"],
  kogmaw: ["[[Q_FLASH]] and [[E_FLASH]] not possible", "Q's [[AS_UP]] is a passive effect", "E's [[SLOW]] continuously applies to targets standing in the area"],
  ksante: ["This is K'Sante: 4700 HP, 329 armor, 201 MR, with [[UNSTOPPABLE]], shield, wall-hop, airborne, 1s cooldown, 15 mana cost. W resets on transform, P deals true damage, armor/MR increase cooldown reduction, Q benefits from ability haste and projectile speed — AAAAAH — Showmaker"],
  leblanc: ["[[W_FLASH]] not possible", "Clone can be controlled with alt + right-click"],
  leesin: ["[[Q_FLASH]] not possible", "Enemies hit by the billiard bounce take bonus damage based on a % of the launched target's max HP"],
  leona: ["W duration extends when hitting an enemy champion", "E has two phases: sword-throw / dash.\nPhase 1 (sword throw) is [[UNSTOPPABLE]].\nPhase 2 (dash) is not [[UNSTOPPABLE]].\nHard CC during phase 1 is ignored; hard CC during phase 2 interrupts the dash", "R applies [[STUN]] in the center, [[SLOW]] elsewhere"],
  lillia: ["Q's [[MS_UP]] is a passive effect so all skills build stacks.\nMax 4 stacks", "[[WALL_HOP]] is not possible with W", "W is interrupted by CC but damage behavior varies:\n1. If CC lands while Lillia is spinning her staff, no damage is dealt\n2. If CC lands while she swings down, movement is interrupted but damage is dealt"],
  lissandra: ["[[W_FLASH]] not possible", "P's [[SLOW]] continuously applies to targets inside the area", "R heals Lissandra when cast on herself"],
  lucian: ["W grants [[MS_UP]] to Lucian when the marked target is attacked by any ally, not just Lucian"],
  lulu: ["[[Q_FLASH]] technically works but the polymorph doesn't follow the flash, so damage is reduced", "R is [[MAX_HP_UP]] so it's effective even at full HP and ignores [[GW]].\nUse it freely for [[AIRBORNE]] and [[SLOW]] utility"],
  lux: ["[[W_FLASH]] and [[R_FLASH]] not possible", "Q [[PIERCE]]s once only", "E's [[SLOW]] continuously applies to targets inside the area", "Cannot TP onto E"],
  malphite: ["[[R_FLASH]] not possible", "E reduces the target's attack speed"],
  malzahar: ["P (passive) is CC immunity.\nTower damage still applies while P is active,\nbut damage is reduced by 90%", "[[R_FLASH]] is extremely powerful"],
  maokai: ["[[R_FLASH]] not possible", "Cannot TP onto saplings", "R's [[MS_UP]] applies when hitting an enemy"],
  masteryi: ["Do not engage first", "Kill participation with R reduces its cooldown by 70% and extends its duration by 7s"],
  mel: ["When Mel's P stacks are sufficiently built on a target, their health bar turns red — Mel's basic attack then executes them.\n(Skills are not involved)", "W is detailed per champion in the box below", "E [[ROOT]] only applies to the center of the ability", "To determine if R will execute, check if the R icon has a golden border"],
  milio: ["[[Q_FLASH]] and [[R_FLASH]] not possible", "Cannot TP onto W", "R cannot be cast while Milio is CC'd"],
  missfortune: ["E's [[SLOW]] continuously applies to targets inside the area", "Use E's [[SLOW]] first, then follow with R.\nR channeling cancels on movement"],
  mordekaiser: ["Q deals increased damage to a single target", "Champion-specific R mechanics are detailed in the box below"],
  morgana: ["[[Q_FLASH]] not possible", "E (Black Shield) grants [[CC_IMMUNE]] while the [[SHIELD]] holds.\nWhen the shield breaks or duration ends, CC immunity ends.\nHowever, if CC hits with enough damage to destroy the shield simultaneously, that CC is still blocked.\nExample: Ashe R deals 500 damage, Morgana E shield is 200 — the shield breaks and 300 damage goes through, but the CC is blocked", "R activates even if stealthed enemies approach nearby. Usability in this case needs confirmation.\nR [[STUN]] applies only if the chain is not broken"],
  naafiri: ["Q's second hit applies [[LIFESTEAL]]", "R was originally a basic skill that was reworked into an ultimate. As a result it no longer has allies blocking for it.\nHowever, R can still be interrupted by CC", "R resets if Naafiri kills or assists within 7s.\nThe initial cast has no [[SHIELD]], but the reset cast grants [[SHIELD]] on use.\nThe reset disappears if unused"],
  nami: ["Q is surprisingly [[SUSPENDING]]", "Having allies hit by R together doubles P's effect on them"],
  nasus: ["R is [[MAX_HP_UP]] so it's effective even at full HP and ignores [[GW]]"],
  nautilus: ["[[Q_FLASH]] not possible.\nQ can pull Nautilus toward walls and structures", "Q has two phases: throw / grapple.\nCC during the throw phase is valid.\nOnce the grapple phase starts and Nautilus moves forward, there is no CC immunity"],
  neeko: ["[[Q_FLASH]] not possible", "Cannot TP onto Neeko's disguise or W clones", "W clone can be kept alive longer with Ctrl+1 emote", "E applies a longer [[ROOT]] when piercing through", "Neeko's R combo flows naturally as R → Flash → Belt", "Neeko's R has three phases:\nPrep phase\n[[SUSPENDING]] phase — Neeko jumps and [[SUSPENDING]]s nearby enemy champions\n[[STUN]] phase — landing deals [[STUN]] in the area", "Enemies outside the area during [[SUSPENDING]] but inside during [[STUN]] will be hit by [[STUN]] and damage"],
  nidalee: ["All cougar form flash combos are not possible", "Hitting with human form Q or W activates Hunting, which resets R cooldown for an immediate transform"],
  nilah: ["Q's passive base effects — [[AR_PEN]], [[HEAL]] on champion attacks, and [[SHIELD]] at max HP — all scale with crit", "W also applies its effects to allies touching Nilah.\nW's [[DMG_REDUCE]] is magic damage only", "E can target allies", "R effects trigger when enemies are grabbed.\nAllies touched by R are also [[HEAL]]ed"],
  nocturne: ["[[Q_FLASH]] not possible", "Q's buffs only activate while standing in the trail", "W's [[AS_UP]] doubles if successfully blocked", "[[FEAR]] only applies if E's tether remains unbroken", "R's [[NEARSIGHT]] leaves only self-vision"],
  nunu: ["During W snowball rolling, recasting throws it", "E creates a circle around Nunu that applies [[ROOT]] at expiration.\nOnly targets hit at least once by E during this time are [[ROOT]]ed", "[[R_FLASH]] not possible. R cancels on any other action", "R's [[SLOW]] continuously applies to targets inside the area"],
  olaf: ["[[Q_FLASH]] not possible. Cannot TP onto Q (axe)", "Hitting E extends R's [[MS_UP]] duration"],
  orianna: ["Cannot TP onto the ball", "E's passive grants bonus armor and MR to whoever holds the ball", "Orianna-Nocturne (Malphite, Yone, Zoe, etc.) combos:\nWhile an ally is within E range and about to be launched, Orianna casts E then immediately R — the ball arrives in time to trigger"],
  ornn: ["P item upgrades begin at level 13, one slot at a time.\nOrnn's Masterwork items are worth 1000g of value", "[[Q_FLASH]], [[W_FLASH]], [[E_FLASH]], [[R_FLASH]] all not possible", "Cannot TP onto Q (pillar)", "Hitting the last part of W makes the target Brittle, which makes the next attack apply bonus CC duration and knockback", "E's [[AIRBORNE]] only triggers on collision with a wall.\nIf the wall belongs to the enemy team, it is destroyed instead", "Both charges of R apply Brittle.\nR's second strike is not [[UNSTOPPABLE]]"],
  pantheon: ["Q's [[CRIT]] applies to enemies below 20% HP", "E's [[INVULNERABLE]] only applies in the direction Pantheon is facing.\nTower damage cannot be blocked", "R has [[AR_PEN]] as a passive base effect"],
  poppy: ["P requires picking up the shield to gain the barrier", "[[E_FLASH]] does not [[INSEC_KICK]]", "[[R_FLASH]] only works with a short charge.\nFull charge version fires toward the nexus instead", "When Poppy's W interrupts a dash, the target can no longer use movement abilities.\n[[GROUNDED]] can be removed by [[CC_CLEANSE]] to re-enable movement skills", "Example: Renekton dashes into Poppy with E — the skill activates and the cooldown runs. Then Poppy's W blocks him, applying [[AIRBORNE]] and [[GROUNDED]].\nIf Renekton uses [[CC_CLEANSE]], E becomes usable again"],
  pyke: ["Pyke's P converts 14 HP into 1 AD", "Using E then W when recalling is effective.\nUsing W then E breaks [[CAMOUFLAGE]]", "[[CAMOUFLAGE]] does not break on flash during W", "E's [[STUN]] triggers as the returning dagger comes back", "R is [[UNSTOPPABLE]] even though it's not stated in the description"],
  qiyana: ["P resets by hitting a different element with W", "Earth Q deals bonus damage to targets below 50% HP", "R has unique hit detection.\nNormally R explodes on wall contact to apply [[STUN]],\nbut if river or brush is in R's path, it explodes and deals damage + [[STUN]] without hitting a wall.\nExample: if the knockback lands on flat ground after passing river/brush, neither the damage nor [[STUN]] will apply"],
  quinn: ["Almost all of Quinn's skills proc P, so effectively all skills have [[REVEALED]]", "Q's [[NEARSIGHT]] cannot be removed by Cleanse.\nOther [[CC_CLEANSE]] methods (not Cleanse) can remove it", "W reveals targets inside brushes"],
  rakan: ["[[W_FLASH]] and [[R_FLASH]] not possible", "R briefly applies bonus [[MS_UP]] upon hitting the first target", "Xayah & Rakan synergy:\nIf Rakan walks up to a recalling Xayah and presses recall, he shares her recall progress.\nRakan gains Xayah's W.\n[[MS_UP]] requires Xayah to attack to trigger on Rakan.\nRakan's E range is doubled when targeting Xayah"],
  rammus: ["P [[AD_UP]] scales with armor and MR", "R jump distance scales with movement speed.\n[[AIRBORNE]] is only possible while in Q (Powerball).\n[[SLOW]] applies 3 additional times in the area"],
  reksai: ["Burrowed vision is reduced for Rek'Sai,\nbut enemy movement is detected as vibrations", "Basic attacking while burrowed launches W — it is not a separate button press.\nTargets hit and nearby enemies are [[AIRBORNE]]d", "Rek'Sai's R cannot be dodged with flash"],
  rell: ["P steals armor and MR from the target\n(target loses, Rell gains)", "Rell's W is complex.\nIn mounted form, W can wall-hop into dismounted form.\nAlso, re-mounting after W and quickly auto-attacking [[GRAB]]s the target.\nAttacking through a thin wall while doing this causes Rell to wall-hop and [[GRAB]] simultaneously", "Mounted form grants constant [[MS_UP]] from W.\nDismounting grants a shield", "E does not [[AA_RESET]]"],
  renata: ["[[Q_FLASH]] and [[E_FLASH]] not possible", "Q hitting champion A applies [[ROOT]].\nRe-casting into champion B applies [[STUN]] to B only", "W target revives at 20% max HP — not a heal, so [[GW]] doesn't apply", "E applies [[SHIELD]] to allies and [[SLOW]] to enemies"],
  renekton: ["[[Q_FLASH]] not possible", "[[W_FLASH]] works by right-clicking a champion then flashing.\nW [[STUN]] lasts twice as long when empowered", "E can be recast once after dealing damage to an enemy", "R is [[MAX_HP_UP]] so it's effective even at full HP and ignores [[GW]]"],
  rengar: ["[[W_FLASH]] not possible", "P [[AD_UP]]: 1, 4, 9, 16, 25% per kill (max 5 kills)", "P's [[MS_UP]] activates on using an empowered skill", "Cannot leap out of a bush by flashing first", "R [[CAMOUFLAGE]] does not break on flash, enabling [[R_FLASH]].\nR reveals the nearest enemy champion and nearby enemies with [[TRUE_SIGHT]].\nR [[AR_SHRED]] only applies to the target leaped on"],
  riven: ["[[Q_FLASH]] and [[W_FLASH]] not possible", "Only Q third cast allows [[WALL_HOP]]", "R has a wind-up animation on first use.\nUsing E then R cancels the animation"],
  rumble: ["Overheating causes [[SILENCE]] on Rumble\nbut grants [[AS_UP]] with bonus damage", "Rumble's E [[MR_SHRED]] doubles when hitting a [[SLOW]]ed target, and overheat E increases the effect by 50%.\nIn short: don't get hit"],
  ryze: ["[[Q_FLASH]] not possible", "P increases max mana by 10% of AP", "Rune and Spellflux are distinct.\nRunes are stacks charged by W and E.\nSpellflux is applied when E hits an enemy", "Both W and E reset Q's cooldown.\nAt 2 runes, Q on a Spellflux target consumes runes to grant [[MS_UP]]", "W applies [[SLOW]] normally.\nW on a Spellflux target applies [[ROOT]]", "[[W_FLASH]] on a Spellflux target is extremely strong", "R cancels if Ryze is CC'd mid-channel.\nAllies can still travel even if CC'd.\nPressing recall during R excludes only the user from the portal.\nAllies become [[INVULNERABLE]] while teleporting, blocking all damage including tower shots.\nWhen teleporting with minions near an enemy tower, aggro is drawn to minions and pets first"],
  samira: ["P grants [[MS_UP]] per rank.\nBasic attacks on an [[AIRBORNE]] target re-apply [[AIRBORNE]] (per-champion cooldown).\nDescription says she dashes to max range — that does not exist; she attacks at standard AA range", "W is detailed per champion in the box below", "R cooldown is 5s.\nBuilding style meter lets you use it frequently.\nR can critically strike"],
  sejuani: ["P only immunizes against [[SLOW]]", "W's [[SLOW]] only applies on the second hit", "R effects and bonus are only applied when hitting a target farther than 1/4 of the range.\n[[SLOW]] and AoE damage only apply beyond 1/4 range"],
  senna: ["P's [[MS_UP]] and [[SLOW]] trigger only when attacking a champion\nand only when the stack burst is triggered", "Cannot TP onto P wraiths.\nWhen [[CRIT]] exceeds 100%, excess crit converts to lifesteal via P", "W is a wide-range [[ROOT]]", "E: allies who enter and exit the mist become wraiths, gaining [[UNTARGETABLE]] and [[MS_UP]]"],
  seraphine: ["[[Q_FLASH]] and [[W_FLASH]] not possible", "P stacks extend Seraphine's basic attack range", "W heals when Seraphine already has a shield.\nConfirmation needed on whether ally-applied shields also proc this", "E applies [[SLOW]] on a direct hit.\n[[SLOW]]ed targets become [[ROOT]]ed.\n[[ROOT]]ed targets become [[STUN]]ed", "R range increases when hitting ally or enemy champions.\n[[R_FLASH]] is extremely powerful"],
  sett: ["[[E_FLASH]] not possible", "W center hit deals true damage.\nUse W carefully", "E [[STUN]] is conditional — both targets must collide with each other.\nMinions can also be the collision partner for [[STUN]]", "R landing damage is amplified on tanks"],
  shaco: ["Shaco deals bonus damage from behind", "Q then attacking from behind applies [[CRIT]].\nQ [[INVISIBILITY]] doesn't break on flash, W, or R.\n(E does break it)", "R (clone) explodes on death, applying AoE [[FEAR]]", "Cannot TP onto the clone,\nbut boxes spawned after clone death allow [[ALLY_TP_OK]]"],
  shen: ["Key mechanic is positioning enemies between Shen and his blade.\nHitting with the blade applies [[SLOW]] and [[AS_UP]].\n[[SLOW]] only applies when the target moves away from Shen", "W deactivates if neither Shen nor allies are inside its area.\nReactivates the moment one enters", "R brings the blade along when teleporting to an ally"],
  shyvana: ["Transform (R) is available at 100 fury.\nFury gained: 1/1.5/2 per second. 2 per basic attack", "R flash is ambiguous — functionally possible but travel distance doesn't increase. However, R flash then E slightly shortens E animation for a quick burst damage + airborne"],
  singed: ["[[E_FLASH]] works but [[INSEC_KICK]] is not possible.\nE's [[ROOT]] only triggers if thrown onto W", "E activates once the throw animation starts — the skill mostly goes through.\nThe landing position is based on where E was cast", "R's [[GW]] only applies to Q"],
  sion: ["[[Q_FLASH]] and [[W_FLASH]] not possible", "Q: charging for 1+ seconds adds [[AIRBORNE]] and [[STUN]] to the release", "Releasing Q by being interrupted (not self-canceling) nullifies the skill", "W increases max HP so [[GW]] has no effect", "R damage and [[STUN]] scale with travel distance.\nColliding with a target causes [[AIRBORNE]], then [[STUN]] on landing"],
  sivir: ["E is detailed per champion in the box below", "During R, basic attacking a champion reduces basic skill cooldowns.\nW (Ricochet) bouncing off champions does NOT reduce cooldowns"],
  skarner: ["Picking up a rock with Q enables AA cancel.\nThe final empowered auto applies [[SLOW]].\nThe thrown rock also applies [[SLOW]]", "E suppresses on collision, then allows ~3 more units of movement.\nHitting a wall during that window applies [[STUN]]", "R can [[SUPPRESS]] up to 3 targets.\nDuring R, Skarner can move and use W and non-flash summoner spells.\n[[MS_UP]] applies on hit"],
  smolder: ["P stacks: 25 splash / 125 bonus projectile / 225 persistent true damage, [[EXECUTE]]", "W's [[SLOW]] continuously applies to targets inside the area", "R [[HEAL]] only activates if Smolder himself is hit by the breath", "E is interrupted by [[HARD_CC]]"],
  sona: ["No skill+flash combos work at all. Needs a rework", "P's [[SLOW]] only applies through E-enhanced basic attacks", "W-enhanced basic attack reduces incoming damage on the target (similar to Exhaust)"],
  soraka: ["Hit Q on enemies, then use W for maximum efficiency", "E's [[SILENCE]] continuously applies to targets inside the area.\nTargets standing in E long enough are [[ROOT]]ed", "R's effect is amplified on targets below 40% HP"],
  swain: ["[[E_FLASH]] not possible", "P is gained from W, E, and kill participation.\nHP recovery is affected by [[GW]].\nMax HP increase is not affected by [[GW]]", "E1 applies [[ROOT]] on hit.\nE2 is [[GRAB]]", "R's [[SLOW]] only applies to the wave released on recast"],
  sylas: ["[[Q_FLASH]] and [[E_FLASH]] not possible", "P is not an AA cancel — it increases attack speed", "E splits into E1 and E2.\nE2 has a throw / dash phase.\nCC during the throw phase is ignored and the dash still triggers.\nHard CC during the dash can interrupt it", "R is detailed per champion in the box below"],
  syndra: ["Cannot TP onto orbs", "P upgrades: 40 orbs empower Q (2 stacks), 60 empower W (add true damage), 80 empower E ([[SLOW]])", "[[W_FLASH]] works both when picking up and throwing", "E stuns enemies hit by flying orbs", "EQ combo doesn't work; use QE.\nWE combo still works"],
  tahmkench: ["Q heals when hitting a champion", "Q applies [[STUN]] when hitting a target with 3 stacks.\nQR can devour targets from long range", "E applies [[SHIELD]] on cast.\nNot casting it provides [[HEAL]] instead", "W wall-hop tag means allies are the ones wall-hopping when devoured"],
  taliyah: ["Q [[SLOW]] only applies from Q cast on Worked Ground", "R is only usable out of combat.\nCannot TP onto R wall.\nR can block Void Herald charge.\nTaking damage while riding R dismounts Taliyah"],
  talon: ["Melee Q applies [[CRIT]].\nKilling a target with Q triggers [[HEAL]]", "W [[SLOW]] only applies on the return", "R [[INVISIBILITY]] does not break on flash", "If Talon is doing less damage than expected, he may be canceling R manually.\nR damage spikes when deactivated via basic attack or Q on a target"],
  taric: ["P's [[MS_UP]] applies for the next 2 basic attacks after using a skill"],
  teemo: ["P's [[AS_UP]] activates when coming out of [[INVISIBILITY]].\n[[INVISIBILITY]] flash rules:\nBush inside → inside: doesn't break\nBush inside → outside: breaks\nBush outside → inside: doesn't break\nBush outside → outside: breaks"],
  thresh: ["[[Q_FLASH]], [[E_FLASH]], [[R_FLASH]] not possible.\nFlash during Q dash phase technically works", "Q has two phases: throw / dash.\nCC during the throw phase is mostly valid.\nHard CC during the dash can interrupt it", "W (lantern) is best placed in the ally's direction of movement"],
  tristana: ["W has two phases: prep / jump.\nCC during prep is valid but the jump still launches Tristana forward.\nThere is no CC immunity during the jump phase", "W resets on:\nKill or assist participation, or\nE (max stacks, 4 charges) detonation", "[[R_FLASH]] allows [[INSEC_KICK]]"],
  trundle: ["P [[HEAL]] triggers when nearby enemies die", "W [[MS_UP]] and bonus healing only apply in the frozen zone.\nBonus healing may not apply to P — report if confirmed", "Cannot TP onto E wall", "R steals armor and MR from the target\n(target loses, Trundle gains)"],
  tryndamere: ["[[E_FLASH]] not possible", "P [[CRIT]] increases with fury level", "Q [[AD_UP]] scales with missing HP", "W activates when nearby enemy champions are present.\nUseful for detecting invisible or stealthed enemies.\nApplies bonus [[SLOW]] when target is facing away", "E cooldown is reduced on crits.\n2x reduction on crits vs champions", "R can be activated under any CC (including silence).\nCannot be used during own W or E cast"],
  twistedfate: ["W card order: Blue (mana) → Red ([[SLOW]]) → Yellow ([[STUN]])", "Hold the gold card, right-click a target, then flash for a smooth [[W_FLASH]] gold card", "E's [[AS_UP]] is a passive effect", "R's [[TRUE_SIGHT]] can be blocked by spell shields (including Banshee's, Night's Edge)"],
  twitch: ["Q [[CAMOUFLAGE]] does not break on flash.\nQ's [[AS_UP]] applies after [[CAMOUFLAGE]] ends.\nQ resets its cooldown when a poisoned champion dies", "W's [[SLOW]] continuously applies to targets inside the area"],
  udyr: ["Udyr's passive is what makes reusing skills his ultimate.\nP cooldown is 50–20s.\nBasic attacking after switching stances reduces P cooldown"],
  urgot: ["[[R_FLASH]] not possible", "Each leg has individual bonus damage and cooldowns", "E has two phases: prep / dash.\nCC during prep is valid but the dash still fires.\nThere is no CC immunity during the dash phase", "R [[EXECUTE]] requires manual recast when the target falls below 25% HP"],
  varus: ["[[E_FLASH]] not possible", "P triggers on any kill (minion, ward, jungle monster).\nKill participation gives 2.5x stacks", "Q pierces with damage reduction after the first target", "W can be activated while charging Q", "E [[SLOW]] and [[GW]] continuously apply to targets inside the area", "R can chain to nearby enemy champions.\nTargets outside the original area are not affected"],
  vayne: ["[[Q_FLASH]] not possible", "P activates when approaching an enemy champion", "Rolling along a wall with Q creates extremely fast AA cancels", "E [[STUN]] only triggers when [[KNOCKBACK]] causes a wall collision.\n[[E_FLASH]] enables [[INSEC_KICK]]", "During R, Q [[INVISIBILITY]] does not break on flash"],
  veigar: ["P grants 1 permanent AP per stack.\n1 stack per skill hit, 5 stacks per kill participation", "Only Q can gain stacks from killing enemies (2 from large units)", "W reduces cooldown by 10% multiplicatively per 50 stacks — theoretically zero-cooldown is possible", "E [[STUN]] only triggers at the outer border of the cage", "R deals maximum damage when the target is below 33% HP"],
  velkoz: ["Q flies slightly farther than the indicated max range", "E applies [[KNOCKBACK]] to nearby targets and [[AIRBORNE]] to distant ones"],
  vex: ["[[W_FLASH]] and [[E_FLASH]] not possible", "Flash can stop R mid-flight"],
  vi: ["Setting up CC first makes it much easier for teammates to follow up", "W effects apply on Q hit", "R targets are visible even through [[INVISIBILITY]].\nEnemies in R's path are [[KNOCKBACK]]ed and [[STUN]]ed"],
  viego: ["P grants [[MS_UP]] when approaching an enemy after possessing a champion", "Using E near a wall reveals Viego's position even through fog of war — be careful when jungling", "R [[SLOW]] only applies to the enemy champion with the lowest HP"],
  viktor: ["Q upgrade adds [[MS_UP]] to Q", "W upgrade adds [[SLOW]] to all skills", "E upgrade adds a second laser explosion", "R upgrade increases R speed and expands radius on kill participation", "W's [[SLOW]] continuously applies to targets inside the area"],
  vladimir: ["P increases max HP based on AP, and AP based on max HP", "W's [[SLOW]] continuously applies to targets inside the area", "E can be cast while using W.\nDisabling smartcast on E is recommended", "R applies 'increased damage taken' — ally damage on R targets is also amplified"],
  volibear: ["[[R_FLASH]] not possible", "P stacks up to 5", "Q has two phases: charge / strike.\nCC during the charge phase cancels Q but refunds the cooldown.\nOnce the strike phase activates, CC is ignored", "Q over a thin wall toward an enemy wall-hops", "W [[HEAL]] requires hitting with W twice", "R is [[MAX_HP_UP]] so it's effective even at full HP and ignores [[GW]]", "R disables towers.\nAlready-fired tower shots cannot be nullified.\nTower aggro cannot be removed"],
  warwick: ["[[E_FLASH]] and [[R_FLASH]] not possible", "Both short and long [[Q_FLASH]] work.\nFor long Q flash: press Q outside range then flash into Q range at the moment Q would fire", "Hold Q when the target uses a movement ability to track them", "W applies to targets below 50% HP.\n2x effect below 25% HP", "R [[PSEUDO_UNSTOPPABLE]] is during the leap phase.\nR [[SUPPRESS]] is during the attack phase"],
  wukong: ["W [[INVISIBILITY]] does not break on flash", "E's [[MS_UP]] also applies to the clone", "R cannot be cancelled by any CC"],
  xayah: ["W does not [[AA_RESET]].\n[[MS_UP]] only activates when feathers touch an enemy champion", "E [[ROOT]] requires hitting 3 or more feathers", "Xayah & Rakan synergy:\nIf Rakan walks up to a recalling Xayah and presses recall, he shares her recall progress.\nRakan gains Xayah's W.\n[[MS_UP]] requires Xayah to attack to trigger on Rakan.\nRakan's E range is doubled when targeting Xayah"],
  xerath: ["[[Q_FLASH]] only works during charging phase, not during firing", "W's effect increases when hitting the center", "E [[STUN]] duration increases with distance", "R shot count: 4/5/6 per rank.\nMoving during cast ends R"],
  xinzhao: ["Q [[AIRBORNE]] triggers on the 3rd hit", "Hitting W extends E range", "R is [[INVULNERABLE]] to attacks from outside the zone.\nHowever, towers, neutral monsters, and epic monsters bypass [[INVULNERABLE]]"],
  yasuo: ["[[W_FLASH]] and [[R_FLASH]] not possible", "P [[AD_UP]] converts excess crit chance into bonus AD", "Q [[AIRBORNE]] triggers on the 3rd cast", "Using Q while mid-dash with E deals AoE damage around Yasuo while moving", "Right-clicking the ground after an E dash prevents Q from becoming a tornado spin", "Yasuo's E has poor CC resistance compared to typical dashes.\nMost dashes ignore [[STUN]], but Yasuo's E stops immediately on [[STUN]]", "R can only target [[AIRBORNE]] enemies.\nR [[AR_SHRED]] applies to all hit targets"],
  yone: ["[[R_FLASH]] not possible", "P [[AD_UP]] converts excess crit chance", "Q [[AIRBORNE]] triggers on the 3rd cast", "W shield scales with the number of enemy champions hit", "E [[PSEUDO_UNSTOPPABLE]] only applies on the return", "E cannot wall-hop on cast.\nThe returning E can wall-hop"],
  yorick: ["Cannot TP onto W", "R cannot be recalled after recasting"],
  yunara: ["Using W then R reduces W cooldown by 80%", "Using E then R resets E"],
  yuumi: ["P heals Yuumi from basic attacks or skills dealing damage,\nand that heal transfers to the attached ally", "E effects (excluding [[MANA_RESTORE]]) apply to Yuumi when unattached.\nWhen attached, effects transfer to the ally plus [[MANA_RESTORE]]", "Getting hit by [[HARD_CC]] while unattached puts W on a 5s cooldown", "R excess healing converts to [[SHIELD]]"],
  zaahen: ["[[E_FLASH]] works but is very difficult", "P at 12 stacks doubles [[AD_UP]].\nFull stacks required for [[REVIVE]]", "Q [[AIRBORNE]] only applies on Q2", "R [[AR_PEN]] is a passive effect"],
  zac: ["[[Q_FLASH]], [[W_FLASH]], [[E_FLASH]] not possible", "P cooldown is 300s.\n[[REVIVE]] is unaffected by [[GW]]", "E [[AIRBORNE]] scales with charge duration", "First hit of R applies [[AIRBORNE]], subsequent hits apply [[SLOW]]"],
  zed: ["Zed must attack alongside his shadow for bonus effects", "[[W_FLASH]] and [[E_FLASH]] not possible", "R makes Zed disappear then reappear behind the target (fixed position)"],
  zeri: ["Q cooldown is affected by ability haste and attack speed.\n70% of excess attack speed converts to AD", "[[CRIT]] can apply to W", "Using E then W fires W through the wall.\nE grants Q 3 pierce charges", "R buffs only trigger when hitting an enemy champion.\nBuff duration is refreshed by basic attacks, Q, or W damage (not item effects)"],
  ziggs: ["[[W_FLASH]] and [[E_FLASH]] not possible", "W can [[EXECUTE]] towers", "R deals maximum damage in the center"],
  zilean: ["Q applies AoE [[STUN]] when two Q's hit the same target, detonating the first", "E applies [[MS_UP]] to allies and [[SLOW]] to enemies", "R lasts 5s; [[REVIVE]] takes 3s.\n[[REVIVE]] heals, so [[GW]] applies"],
  zoe: ["First [[Q_FLASH]] not possible; second Q can [[Q_FLASH]]", "[[E_FLASH]] not possible", "Core gameplay: keep cycling P through Q1, Q2, W, E, R", "Q damage increases with travel distance (appears to have an upper limit)", "When Zoe collects a flash from W,\nusing Zoe's flash consumes W's flash first", "E travels along walls and stays as a ground trap if it hits nothing", "E [[SLEEP]] doubles damage from the next basic attack or skill — including ally attacks"],
  zyra: ["[[R_FLASH]] not possible", "Cannot TP onto seeds.\nPlants allow [[ALLY_TP_OK]]", "Q-grown plant: 'Thorn Spitter' (long range)\nE-grown plant: 'Vine Lasher' (applies [[SLOW]])\nR does not grow plants — it only buffs existing ones", "Enemies stepping on W seeds reveal themselves via [[TRUE_SIGHT]].\nP-spawned plants do not have this effect"],
};

const dir = 'app/data/champs';

for (const [id, enNotes] of Object.entries(translations)) {
  const path = `${dir}/${id}.ts`;
  let content;
  try {
    content = readFileSync(path, 'utf8');
  } catch {
    console.error(`File not found: ${path}`);
    continue;
  }

  // Build the en array string
  const items = enNotes.map(s => JSON.stringify(s)).join(', ');
  const newContent = content.replace(/en:\s*\[\s*\](\s*\n\s*\}[^}]*\n[^e]|(?=\s*\n\s*\},\s*\n\s*vision))/,
    `en: [${items}]$1`
  );

  if (newContent === content) {
    // Try simpler pattern - just replace the first `en: []` in notes section
    const notesIdx = content.indexOf('notes:');
    if (notesIdx === -1) {
      console.error(`No notes section in ${id}`);
      continue;
    }
    const beforeNotes = content.slice(0, notesIdx);
    const afterNotes = content.slice(notesIdx);
    const replaced = afterNotes.replace(/en:\s*\[\s*\]/, `en: [${items}]`);
    if (replaced === afterNotes) {
      console.error(`No replacement made for ${id}`);
      continue;
    }
    writeFileSync(path, beforeNotes + replaced, 'utf8');
    console.log(`Updated ${id}.ts`);
  } else {
    writeFileSync(path, newContent, 'utf8');
    console.log(`Updated ${id}.ts`);
  }
}
